- platform: generic
  still_image_url: !secret weather_url
  name: Weather

- platform: generic
  still_image_url: !secret weather_radar
  name: Weather Radar

#- platform: mjpeg
#  mjpeg_url: http://10.0.1.26:8080/?action=stream
#  name: Outdoor

- platform: arlo
  ffmpeg_binary: '/usr/bin/ffmpeg'
  ffmpeg_arguments: '-q:v 5'

- platform: local_file
  name: Mail
  file_path: /opt/homeassistant/mail/mail.gif
